# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack@gem
title: CoderDojo Docklands
description: Code Club for kids
repository: tangowhisky37.github.io/CoderDojoDocklands/


## Customizaton
## ========================================================================================

font: "'Noto Sans', Helvetica, Arial, sans-serif"
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
google_fonts: "Roboto+Slab:700|Noto+Sans:400,400i,700,700i"

## Sidebar image and theme color of the site.
accent_image: Images/term_1_2019_pic_2.jpg
accent_color: '#4fb1ba'

defaults:
  - scope:
      path: Pages/site/newsupdates.md
    values:
      menu: true
      order: 1
  - scope:
      path: Pages/site/signup.md
    values:
      menu: true
      order: 2
  - scope: 
      path: Pages/site/billmaterial.md
    values: 
      menu: true
      order: 3
  - scope:
      path: Pages/site/projecttools.md
    values:
      menu: true
      order: 4
  - scope: 
      path: Pages/site/misc.md
    values:
      menu: true
      order: 5

author:
  social:
    twitter: https://twitter.com/tangowhisky37
    github:  https://github.com/tangowhisky37/CoderDojo
    email:   mailto:docklandsdojo@hack2.live
  name: Trevor Warren
  email: trevor@hack2.live
